// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package employeeproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RequestField struct {
	Avatar                   string   `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Prefix                   string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	FirstName                string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName               string   `protobuf:"bytes,4,opt,name=middleName,proto3" json:"middleName,omitempty"`
	LastName                 string   `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ContactEmail             string   `protobuf:"bytes,6,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	ContactMobile            string   `protobuf:"bytes,7,opt,name=contactMobile,proto3" json:"contactMobile,omitempty"`
	ContactPhone             string   `protobuf:"bytes,8,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	AddressStreet            string   `protobuf:"bytes,9,opt,name=addressStreet,proto3" json:"addressStreet,omitempty"`
	AddressCity              string   `protobuf:"bytes,10,opt,name=addressCity,proto3" json:"addressCity,omitempty"`
	AddressPostCode          string   `protobuf:"bytes,11,opt,name=addressPostCode,proto3" json:"addressPostCode,omitempty"`
	AddressState             string   `protobuf:"bytes,12,opt,name=addressState,proto3" json:"addressState,omitempty"`
	AddressCountry           string   `protobuf:"bytes,13,opt,name=addressCountry,proto3" json:"addressCountry,omitempty"`
	EmergencyContactFullName string   `protobuf:"bytes,14,opt,name=emergencyContactFullName,proto3" json:"emergencyContactFullName,omitempty"`
	EmergencyContactMobile   string   `protobuf:"bytes,15,opt,name=emergencyContactMobile,proto3" json:"emergencyContactMobile,omitempty"`
	EmployeeTitle            string   `protobuf:"bytes,16,opt,name=employeeTitle,proto3" json:"employeeTitle,omitempty"`
	SupervisorID             int32    `protobuf:"varint,17,opt,name=supervisorID,proto3" json:"supervisorID,omitempty"`
	HiredDate                int64    `protobuf:"varint,18,opt,name=hiredDate,proto3" json:"hiredDate,omitempty"`
	SavannahUser             bool     `protobuf:"varint,19,opt,name=savannahUser,proto3" json:"savannahUser,omitempty"`
	Username                 string   `protobuf:"bytes,20,opt,name=username,proto3" json:"username,omitempty"`
	Password                 string   `protobuf:"bytes,21,opt,name=password,proto3" json:"password,omitempty"`
	RePassword               string   `protobuf:"bytes,22,opt,name=rePassword,proto3" json:"rePassword,omitempty"`
	TimeZone                 string   `protobuf:"bytes,23,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	Currency                 string   `protobuf:"bytes,24,opt,name=currency,proto3" json:"currency,omitempty"`
	Role                     string   `protobuf:"bytes,25,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RequestField) Reset()         { *m = RequestField{} }
func (m *RequestField) String() string { return proto.CompactTextString(m) }
func (*RequestField) ProtoMessage()    {}
func (*RequestField) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *RequestField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestField.Unmarshal(m, b)
}
func (m *RequestField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestField.Marshal(b, m, deterministic)
}
func (m *RequestField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestField.Merge(m, src)
}
func (m *RequestField) XXX_Size() int {
	return xxx_messageInfo_RequestField.Size(m)
}
func (m *RequestField) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestField.DiscardUnknown(m)
}

var xxx_messageInfo_RequestField proto.InternalMessageInfo

func (m *RequestField) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *RequestField) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *RequestField) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RequestField) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *RequestField) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RequestField) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *RequestField) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *RequestField) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *RequestField) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *RequestField) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *RequestField) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *RequestField) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *RequestField) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

func (m *RequestField) GetEmergencyContactFullName() string {
	if m != nil {
		return m.EmergencyContactFullName
	}
	return ""
}

func (m *RequestField) GetEmergencyContactMobile() string {
	if m != nil {
		return m.EmergencyContactMobile
	}
	return ""
}

func (m *RequestField) GetEmployeeTitle() string {
	if m != nil {
		return m.EmployeeTitle
	}
	return ""
}

func (m *RequestField) GetSupervisorID() int32 {
	if m != nil {
		return m.SupervisorID
	}
	return 0
}

func (m *RequestField) GetHiredDate() int64 {
	if m != nil {
		return m.HiredDate
	}
	return 0
}

func (m *RequestField) GetSavannahUser() bool {
	if m != nil {
		return m.SavannahUser
	}
	return false
}

func (m *RequestField) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RequestField) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RequestField) GetRePassword() string {
	if m != nil {
		return m.RePassword
	}
	return ""
}

func (m *RequestField) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *RequestField) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *RequestField) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type RawRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RawRequest) Reset()         { *m = RawRequest{} }
func (m *RawRequest) String() string { return proto.CompactTextString(m) }
func (*RawRequest) ProtoMessage()    {}
func (*RawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *RawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawRequest.Unmarshal(m, b)
}
func (m *RawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawRequest.Marshal(b, m, deterministic)
}
func (m *RawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawRequest.Merge(m, src)
}
func (m *RawRequest) XXX_Size() int {
	return xxx_messageInfo_RawRequest.Size(m)
}
func (m *RawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawRequest proto.InternalMessageInfo

func (m *RawRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Field                *RequestField  `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type UpdateRequest struct {
	Header               *RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id                   int32          `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Action               string         `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Field                *RequestField  `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UpdateRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UpdateRequest) GetField() *RequestField {
	if m != nil {
		return m.Field
	}
	return nil
}

type DataResponse struct {
	StatusCode           int32              `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *DataResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *DataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DataResponse) GetData() *DataResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataResponse_Data struct {
	Id                       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Avatar                   string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Prefix                   string   `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	FirstName                string   `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	MiddleName               string   `protobuf:"bytes,5,opt,name=middleName,proto3" json:"middleName,omitempty"`
	LastName                 string   `protobuf:"bytes,6,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ContactEmail             string   `protobuf:"bytes,7,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	ContactMobile            string   `protobuf:"bytes,8,opt,name=contactMobile,proto3" json:"contactMobile,omitempty"`
	ContactPhone             string   `protobuf:"bytes,9,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	AddressStreet            string   `protobuf:"bytes,10,opt,name=addressStreet,proto3" json:"addressStreet,omitempty"`
	AddressCity              string   `protobuf:"bytes,11,opt,name=addressCity,proto3" json:"addressCity,omitempty"`
	AddressPostCode          string   `protobuf:"bytes,12,opt,name=addressPostCode,proto3" json:"addressPostCode,omitempty"`
	AddressState             string   `protobuf:"bytes,13,opt,name=addressState,proto3" json:"addressState,omitempty"`
	AddressCountry           string   `protobuf:"bytes,14,opt,name=addressCountry,proto3" json:"addressCountry,omitempty"`
	EmergencyContactFullName string   `protobuf:"bytes,15,opt,name=emergencyContactFullName,proto3" json:"emergencyContactFullName,omitempty"`
	EmergencyContactMobile   string   `protobuf:"bytes,16,opt,name=emergencyContactMobile,proto3" json:"emergencyContactMobile,omitempty"`
	EmployeeTitle            string   `protobuf:"bytes,17,opt,name=employeeTitle,proto3" json:"employeeTitle,omitempty"`
	Supervisor               string   `protobuf:"bytes,18,opt,name=supervisor,proto3" json:"supervisor,omitempty"`
	HiredDate                string   `protobuf:"bytes,19,opt,name=hiredDate,proto3" json:"hiredDate,omitempty"`
	SavannahUser             string   `protobuf:"bytes,20,opt,name=savannahUser,proto3" json:"savannahUser,omitempty"`
	Username                 string   `protobuf:"bytes,21,opt,name=username,proto3" json:"username,omitempty"`
	Password                 string   `protobuf:"bytes,22,opt,name=password,proto3" json:"password,omitempty"`
	RePassword               string   `protobuf:"bytes,23,opt,name=rePassword,proto3" json:"rePassword,omitempty"`
	TimeZone                 string   `protobuf:"bytes,24,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	Currency                 string   `protobuf:"bytes,25,opt,name=currency,proto3" json:"currency,omitempty"`
	Role                     string   `protobuf:"bytes,26,opt,name=role,proto3" json:"role,omitempty"`
	ClientName               string   `protobuf:"bytes,27,opt,name=clientName,proto3" json:"clientName,omitempty"`
	CreatedDate              string   `protobuf:"bytes,28,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	CreatedBy                string   `protobuf:"bytes,29,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	LastModifiedBy           string   `protobuf:"bytes,30,opt,name=lastModifiedBy,proto3" json:"lastModifiedBy,omitempty"`
	LastModifiedDate         string   `protobuf:"bytes,31,opt,name=lastModifiedDate,proto3" json:"lastModifiedDate,omitempty"`
	RecordState              string   `protobuf:"bytes,32,opt,name=recordState,proto3" json:"recordState,omitempty"`
	LastLogin                string   `protobuf:"bytes,33,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *DataResponse_Data) Reset()         { *m = DataResponse_Data{} }
func (m *DataResponse_Data) String() string { return proto.CompactTextString(m) }
func (*DataResponse_Data) ProtoMessage()    {}
func (*DataResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6, 0}
}

func (m *DataResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse_Data.Unmarshal(m, b)
}
func (m *DataResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse_Data.Marshal(b, m, deterministic)
}
func (m *DataResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse_Data.Merge(m, src)
}
func (m *DataResponse_Data) XXX_Size() int {
	return xxx_messageInfo_DataResponse_Data.Size(m)
}
func (m *DataResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse_Data proto.InternalMessageInfo

func (m *DataResponse_Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataResponse_Data) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *DataResponse_Data) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *DataResponse_Data) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *DataResponse_Data) GetMiddleName() string {
	if m != nil {
		return m.MiddleName
	}
	return ""
}

func (m *DataResponse_Data) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *DataResponse_Data) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *DataResponse_Data) GetContactMobile() string {
	if m != nil {
		return m.ContactMobile
	}
	return ""
}

func (m *DataResponse_Data) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *DataResponse_Data) GetAddressStreet() string {
	if m != nil {
		return m.AddressStreet
	}
	return ""
}

func (m *DataResponse_Data) GetAddressCity() string {
	if m != nil {
		return m.AddressCity
	}
	return ""
}

func (m *DataResponse_Data) GetAddressPostCode() string {
	if m != nil {
		return m.AddressPostCode
	}
	return ""
}

func (m *DataResponse_Data) GetAddressState() string {
	if m != nil {
		return m.AddressState
	}
	return ""
}

func (m *DataResponse_Data) GetAddressCountry() string {
	if m != nil {
		return m.AddressCountry
	}
	return ""
}

func (m *DataResponse_Data) GetEmergencyContactFullName() string {
	if m != nil {
		return m.EmergencyContactFullName
	}
	return ""
}

func (m *DataResponse_Data) GetEmergencyContactMobile() string {
	if m != nil {
		return m.EmergencyContactMobile
	}
	return ""
}

func (m *DataResponse_Data) GetEmployeeTitle() string {
	if m != nil {
		return m.EmployeeTitle
	}
	return ""
}

func (m *DataResponse_Data) GetSupervisor() string {
	if m != nil {
		return m.Supervisor
	}
	return ""
}

func (m *DataResponse_Data) GetHiredDate() string {
	if m != nil {
		return m.HiredDate
	}
	return ""
}

func (m *DataResponse_Data) GetSavannahUser() string {
	if m != nil {
		return m.SavannahUser
	}
	return ""
}

func (m *DataResponse_Data) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DataResponse_Data) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DataResponse_Data) GetRePassword() string {
	if m != nil {
		return m.RePassword
	}
	return ""
}

func (m *DataResponse_Data) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *DataResponse_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *DataResponse_Data) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *DataResponse_Data) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *DataResponse_Data) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *DataResponse_Data) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *DataResponse_Data) GetLastModifiedDate() string {
	if m != nil {
		return m.LastModifiedDate
	}
	return ""
}

func (m *DataResponse_Data) GetRecordState() string {
	if m != nil {
		return m.RecordState
	}
	return ""
}

func (m *DataResponse_Data) GetLastLogin() string {
	if m != nil {
		return m.LastLogin
	}
	return ""
}

type RawResponse struct {
	StatusCode           int32             `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RawResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RawResponse) Reset()         { *m = RawResponse{} }
func (m *RawResponse) String() string { return proto.CompactTextString(m) }
func (*RawResponse) ProtoMessage()    {}
func (*RawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *RawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse.Unmarshal(m, b)
}
func (m *RawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse.Marshal(b, m, deterministic)
}
func (m *RawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse.Merge(m, src)
}
func (m *RawResponse) XXX_Size() int {
	return xxx_messageInfo_RawResponse.Size(m)
}
func (m *RawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse proto.InternalMessageInfo

func (m *RawResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RawResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RawResponse) GetData() *RawResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RawResponse_Data struct {
	Avatar               []string `protobuf:"bytes,1,rep,name=avatar,proto3" json:"avatar,omitempty"`
	TimeZone             []string `protobuf:"bytes,3,rep,name=timeZone,proto3" json:"timeZone,omitempty"`
	Currency             []string `protobuf:"bytes,4,rep,name=currency,proto3" json:"currency,omitempty"`
	Role                 []string `protobuf:"bytes,5,rep,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawResponse_Data) Reset()         { *m = RawResponse_Data{} }
func (m *RawResponse_Data) String() string { return proto.CompactTextString(m) }
func (*RawResponse_Data) ProtoMessage()    {}
func (*RawResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7, 0}
}

func (m *RawResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawResponse_Data.Unmarshal(m, b)
}
func (m *RawResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawResponse_Data.Marshal(b, m, deterministic)
}
func (m *RawResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawResponse_Data.Merge(m, src)
}
func (m *RawResponse_Data) XXX_Size() int {
	return xxx_messageInfo_RawResponse_Data.Size(m)
}
func (m *RawResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RawResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RawResponse_Data proto.InternalMessageInfo

func (m *RawResponse_Data) GetAvatar() []string {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *RawResponse_Data) GetTimeZone() []string {
	if m != nil {
		return m.TimeZone
	}
	return nil
}

func (m *RawResponse_Data) GetCurrency() []string {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *RawResponse_Data) GetRole() []string {
	if m != nil {
		return m.Role
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "employeeproto.RequestHeader")
	proto.RegisterType((*RequestField)(nil), "employeeproto.RequestField")
	proto.RegisterType((*RawRequest)(nil), "employeeproto.RawRequest")
	proto.RegisterType((*GetRequest)(nil), "employeeproto.GetRequest")
	proto.RegisterType((*CreateRequest)(nil), "employeeproto.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "employeeproto.UpdateRequest")
	proto.RegisterType((*DataResponse)(nil), "employeeproto.DataResponse")
	proto.RegisterType((*DataResponse_Data)(nil), "employeeproto.DataResponse.Data")
	proto.RegisterType((*RawResponse)(nil), "employeeproto.RawResponse")
	proto.RegisterType((*RawResponse_Data)(nil), "employeeproto.RawResponse.Data")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 952 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0xc7, 0x4b, 0x9f, 0x96, 0x5a, 0x92, 0xed, 0x4c, 0x12, 0x67, 0x2c, 0x9b, 0x44, 0xa8, 0x80,
	0x52, 0x71, 0x70, 0x15, 0x4e, 0x8a, 0x03, 0x05, 0x97, 0xc8, 0x49, 0xa0, 0x8a, 0x50, 0xae, 0x85,
	0x5c, 0xb8, 0x4d, 0x76, 0xdb, 0xf6, 0xc0, 0x6a, 0x47, 0xcc, 0x8c, 0xec, 0xe8, 0x31, 0x78, 0x03,
	0x1e, 0x0d, 0x6e, 0x79, 0x0c, 0x6a, 0x7a, 0x76, 0xa5, 0x5d, 0xd9, 0x5a, 0x64, 0x74, 0x53, 0xff,
	0xbb, 0xa7, 0xa7, 0xa7, 0xb7, 0xe7, 0x37, 0x82, 0x9e, 0x41, 0x7d, 0x2d, 0x43, 0x3c, 0x99, 0x6a,
	0x65, 0x15, 0xeb, 0xe1, 0x64, 0x1a, 0xab, 0x39, 0x22, 0x99, 0xc3, 0xcf, 0xa1, 0x17, 0xe0, 0x1f,
	0x33, 0x34, 0xf6, 0x7b, 0x14, 0x11, 0x6a, 0xf6, 0x08, 0x1a, 0x56, 0xfd, 0x8e, 0x09, 0xaf, 0x0c,
	0x2a, 0xa3, 0x76, 0xe0, 0x8d, 0xe1, 0xc7, 0x26, 0x74, 0xd3, 0xb8, 0xd7, 0x12, 0xe3, 0x88, 0x1d,
	0x40, 0x53, 0x5c, 0x0b, 0x2b, 0x74, 0x1a, 0x97, 0x5a, 0x4e, 0x9f, 0x6a, 0xbc, 0x90, 0x1f, 0x78,
	0xd5, 0xeb, 0xde, 0x62, 0xc7, 0xd0, 0xbe, 0x90, 0xda, 0xd8, 0x9f, 0xc4, 0x04, 0x79, 0x8d, 0x5c,
	0x4b, 0x81, 0x3d, 0x05, 0x98, 0xc8, 0x28, 0x8a, 0x91, 0xdc, 0x75, 0x72, 0xe7, 0x14, 0xd6, 0x87,
	0x56, 0x2c, 0xd2, 0xc5, 0x0d, 0xf2, 0x2e, 0x6c, 0x36, 0x84, 0x6e, 0xa8, 0x12, 0x2b, 0x42, 0xfb,
	0x6a, 0x22, 0x64, 0xcc, 0x9b, 0xe4, 0x2f, 0x68, 0xec, 0x33, 0xe8, 0xa5, 0xf6, 0x5b, 0xf5, 0x5e,
	0xc6, 0xc8, 0x77, 0x28, 0xa8, 0x28, 0xe6, 0x32, 0x9d, 0x5f, 0xa9, 0x04, 0x79, 0xab, 0x90, 0x89,
	0x34, 0x97, 0x49, 0x44, 0x91, 0x46, 0x63, 0x7e, 0xb6, 0x1a, 0xd1, 0xf2, 0xb6, 0xcf, 0x54, 0x10,
	0xd9, 0x00, 0x3a, 0xa9, 0x30, 0x96, 0x76, 0xce, 0x81, 0x62, 0xf2, 0x12, 0x1b, 0xc1, 0x5e, 0x6a,
	0x9e, 0x2b, 0x63, 0xc7, 0x2a, 0x42, 0xde, 0xa1, 0xa8, 0x55, 0xd9, 0x55, 0xb5, 0x48, 0x2e, 0x2c,
	0xf2, 0xae, 0xaf, 0x2a, 0xaf, 0xb1, 0x2f, 0x60, 0x37, 0x4b, 0xae, 0x66, 0x89, 0xd5, 0x73, 0xde,
	0xa3, 0xa8, 0x15, 0x95, 0x7d, 0x03, 0x1c, 0x27, 0xa8, 0x2f, 0x31, 0x09, 0xe7, 0x63, 0x7f, 0xac,
	0xd7, 0xb3, 0x38, 0xa6, 0xbe, 0xee, 0xd2, 0x8a, 0xb5, 0x7e, 0xf6, 0x35, 0x1c, 0xac, 0xfa, 0xd2,
	0x66, 0xee, 0xd1, 0xca, 0x35, 0x5e, 0xd7, 0xb1, 0x6c, 0xe4, 0x7e, 0x91, 0x36, 0x46, 0xbe, 0xef,
	0x3b, 0x56, 0x10, 0xdd, 0x29, 0xcd, 0x6c, 0xea, 0x26, 0xd5, 0x28, 0xfd, 0xc3, 0x19, 0x7f, 0x30,
	0xa8, 0x8c, 0x1a, 0x41, 0x41, 0x73, 0x33, 0x74, 0x25, 0x35, 0x46, 0x67, 0xae, 0x0d, 0x6c, 0x50,
	0x19, 0xd5, 0x82, 0xa5, 0x40, 0x19, 0xc4, 0xb5, 0x48, 0x12, 0x71, 0xf5, 0xce, 0xa0, 0xe6, 0x0f,
	0x07, 0x95, 0x51, 0x2b, 0x28, 0x68, 0x6e, 0x8e, 0x66, 0x06, 0x75, 0xe2, 0xce, 0xfb, 0xc8, 0xcf,
	0x51, 0x66, 0x3b, 0xdf, 0x54, 0x18, 0x73, 0xa3, 0x74, 0xc4, 0x1f, 0x7b, 0x5f, 0x66, 0xbb, 0xf9,
	0xd4, 0x78, 0x9e, 0x79, 0x0f, 0xfc, 0x7c, 0x2e, 0x15, 0xb7, 0xd6, 0xca, 0x09, 0xfe, 0xea, 0xa6,
	0xe6, 0x89, 0x5f, 0x9b, 0xd9, 0xce, 0x17, 0xce, 0xb4, 0x76, 0x8d, 0xe1, 0xdc, 0xfb, 0x32, 0x9b,
	0x31, 0xa8, 0x6b, 0x15, 0x23, 0x3f, 0x24, 0x9d, 0x7e, 0x0f, 0x5f, 0x02, 0x04, 0xe2, 0x26, 0xbd,
	0x6c, 0xec, 0x05, 0x34, 0xaf, 0xe8, 0x62, 0xd2, 0x3d, 0xeb, 0x9c, 0x1e, 0x9f, 0x14, 0xee, 0xef,
	0x49, 0xe1, 0xf2, 0x06, 0x69, 0xec, 0x30, 0x00, 0x78, 0x83, 0x76, 0xab, 0x1c, 0x6c, 0x17, 0xaa,
	0x32, 0xa2, 0x5b, 0xdc, 0x08, 0xaa, 0x32, 0x1a, 0x7e, 0x80, 0xde, 0x58, 0xa3, 0xb0, 0xb8, 0x5d,
	0xda, 0xaf, 0xa0, 0x71, 0xe1, 0x08, 0x42, 0x99, 0x3b, 0xa7, 0x47, 0x77, 0x2f, 0x22, 0xc8, 0x04,
	0x3e, 0x72, 0xf8, 0x57, 0x05, 0x7a, 0xef, 0xa6, 0xd1, 0xd6, 0x5b, 0xaf, 0x9c, 0x88, 0x18, 0x16,
	0x5a, 0xa9, 0x92, 0x14, 0x48, 0xa9, 0xb5, 0x2c, 0xb1, 0xbe, 0x71, 0x89, 0xff, 0xb4, 0xa1, 0x7b,
	0x26, 0xac, 0x08, 0xd0, 0x4c, 0x55, 0x62, 0x88, 0x68, 0xc6, 0x0a, 0x3b, 0x33, 0x74, 0xb5, 0x2b,
	0xb4, 0x67, 0x4e, 0x61, 0x1c, 0x76, 0x26, 0x68, 0x8c, 0xb8, 0xc4, 0x14, 0x94, 0x99, 0xc9, 0x5e,
	0x40, 0x3d, 0x12, 0x56, 0x50, 0x4d, 0x9d, 0xd3, 0xc1, 0xca, 0xe6, 0xf9, 0x4d, 0xbc, 0x41, 0xd1,
	0xfd, 0xbf, 0x5b, 0x50, 0x77, 0x66, 0x7a, 0x48, 0x0f, 0xe5, 0xec, 0x90, 0x1e, 0xd4, 0xd5, 0x35,
	0xa0, 0xae, 0xad, 0x07, 0x75, 0xbd, 0x1c, 0xd4, 0x8d, 0x52, 0x50, 0x37, 0xff, 0x03, 0xd4, 0x3b,
	0x9b, 0x80, 0xba, 0xb5, 0x09, 0xa8, 0xdb, 0x9b, 0x80, 0x1a, 0x36, 0x00, 0x75, 0x67, 0x23, 0x50,
	0x77, 0x37, 0x03, 0x75, 0x6f, 0x23, 0x50, 0xef, 0xde, 0x1b, 0xd4, 0x7b, 0xff, 0x1b, 0xd4, 0xfb,
	0xf7, 0x03, 0xf5, 0x83, 0xbb, 0x40, 0xed, 0x06, 0x7b, 0x01, 0x65, 0xa2, 0x70, 0x3b, 0xc8, 0x29,
	0x45, 0x48, 0x3f, 0xf4, 0xf3, 0xb3, 0x1e, 0xd2, 0x1e, 0xc2, 0xeb, 0x21, 0xfd, 0xb8, 0x04, 0xd2,
	0x07, 0xa5, 0x90, 0x7e, 0x52, 0x0a, 0x69, 0x5e, 0x02, 0xe9, 0xc3, 0x35, 0x90, 0xee, 0x2f, 0x21,
	0xed, 0xf6, 0x0a, 0x63, 0x89, 0x89, 0x9f, 0xf4, 0x23, 0xbf, 0xd7, 0x52, 0x71, 0x73, 0x15, 0x12,
	0x2c, 0x7d, 0x1f, 0x8e, 0xfd, 0x5c, 0xe5, 0x24, 0xd7, 0xa7, 0xd4, 0x7c, 0x39, 0xe7, 0x9f, 0xf8,
	0x3e, 0x2d, 0x04, 0x37, 0x27, 0xee, 0xde, 0xbc, 0x55, 0x91, 0xbc, 0x90, 0x14, 0xf2, 0xd4, 0xcf,
	0x49, 0x51, 0x65, 0x5f, 0xc2, 0x7e, 0x5e, 0xa1, 0xcd, 0x9e, 0x51, 0xe4, 0x2d, 0xdd, 0xd5, 0xa4,
	0x31, 0x54, 0x3a, 0xf2, 0xe3, 0x39, 0xf0, 0x35, 0xe5, 0x24, 0x57, 0x93, 0x5b, 0xf5, 0xa3, 0xba,
	0x94, 0x09, 0xff, 0xd4, 0xd7, 0xb4, 0x10, 0x86, 0x1f, 0x2b, 0xd0, 0xa1, 0x97, 0x69, 0x6b, 0xc4,
	0x3d, 0x2f, 0x20, 0xee, 0xd9, 0x2a, 0x5f, 0x97, 0x7b, 0xe4, 0x09, 0xf7, 0x5b, 0x0a, 0xb8, 0xfc,
	0x3f, 0xcf, 0x5a, 0x0e, 0x68, 0xf9, 0xcf, 0x5b, 0x23, 0xcf, 0xdd, 0x9f, 0xb7, 0xee, 0x7d, 0xb7,
	0x3e, 0x6f, 0x83, 0x74, 0xfa, 0x7d, 0xfa, 0x67, 0x15, 0x5a, 0xaf, 0xd2, 0xa2, 0xd8, 0xb7, 0x50,
	0x0b, 0xc4, 0x0d, 0x3b, 0xbc, 0xab, 0x4c, 0x7a, 0x09, 0xfa, 0xfd, 0xf5, 0x27, 0x60, 0x63, 0x68,
	0xfa, 0x67, 0x93, 0xad, 0x3e, 0x52, 0x85, 0xd7, 0xb4, 0x7f, 0x54, 0x02, 0x7a, 0xf6, 0x1d, 0xd4,
	0xde, 0xa0, 0xbd, 0x55, 0xc2, 0xf2, 0x8d, 0x2f, 0x5f, 0x3e, 0x86, 0xa6, 0x7f, 0x3f, 0x6f, 0xd5,
	0x50, 0x78, 0x56, 0x4b, 0x93, 0xbc, 0x6f, 0x92, 0xf6, 0xfc, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf8, 0xc7, 0x18, 0x83, 0x50, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeClient is the client API for Employee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeClient interface {
	Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type employeeClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeClient(cc *grpc.ClientConn) EmployeeClient {
	return &employeeClient{cc}
}

func (c *employeeClient) Raw(ctx context.Context, in *RawRequest, opts ...grpc.CallOption) (*RawResponse, error) {
	out := new(RawResponse)
	err := c.cc.Invoke(ctx, "/employeeproto.Employee/Raw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/employeeproto.Employee/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/employeeproto.Employee/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/employeeproto.Employee/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServer is the server API for Employee service.
type EmployeeServer interface {
	Raw(context.Context, *RawRequest) (*RawResponse, error)
	Create(context.Context, *CreateRequest) (*DataResponse, error)
	Get(context.Context, *GetRequest) (*DataResponse, error)
	Update(context.Context, *UpdateRequest) (*DataResponse, error)
}

// UnimplementedEmployeeServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServer struct {
}

func (*UnimplementedEmployeeServer) Raw(ctx context.Context, req *RawRequest) (*RawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Raw not implemented")
}
func (*UnimplementedEmployeeServer) Create(ctx context.Context, req *CreateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedEmployeeServer) Get(ctx context.Context, req *GetRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedEmployeeServer) Update(ctx context.Context, req *UpdateRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterEmployeeServer(s *grpc.Server, srv EmployeeServer) {
	s.RegisterService(&_Employee_serviceDesc, srv)
}

func _Employee_Raw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Raw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeproto.Employee/Raw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Raw(ctx, req.(*RawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeproto.Employee/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeproto.Employee/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employeeproto.Employee/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Employee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "employeeproto.Employee",
	HandlerType: (*EmployeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Raw",
			Handler:    _Employee_Raw_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Employee_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Employee_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Employee_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
